name: social_auth
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  auto_route: ^3.2.4
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  equatable: ^2.0.3
  firebase_auth: ^3.3.15
  firebase_core: ^1.15.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  # flutter_secure_storage: ^5.0.2
  freezed_annotation: ^2.0.1
  get_it: ^7.2.0
  google_sign_in: ^5.3.0
  injectable: ^1.5.3
  json_annotation: ^4.4.0

dev_dependencies:
  auto_route_generator: ^3.2.3
  build_runner: ^2.1.10
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.0.2
  injectable_generator: ^1.5.3
  json_serializable: ^6.1.6

flutter:

  uses-material-design: true
